# Generated by Django 5.1.1 on 2025-01-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='desingnation',
            new_name='designation',
        ),
    ]
